=== rupeshpurum/Shell-Scripts/TL1/profiles/fujitsu-flashwave-9500.pro_FILES/fujitsu-flashwave-9500/pm/pmProfile.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE pmProfile PUBLIC "pm/pmProfile.dtd" "pmProfile.dtd">

    <pmProfile>
    ...
    </pmProfile>
-->

<!ELEMENT pmProfile (metricGroup)+>
<!ATTLIST pmProfile
    name CDATA #REQUIRED
    version CDATA #IMPLIED
  >

<!ELEMENT metricGroup (metric)+>
<!ATTLIST metricGroup
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    protocol (SNMP|TL1|NAGIOS|SYSTEM|METRIC|CORBA|SERVICE|ASCII|API) #REQUIRED
    displayType (Normal|Composite|normal|composite|NORMAL|COMPOSITE) #REQUIRED
	reference CDATA #IMPLIED
  >

<!ELEMENT metric (parameter|min|value|max|history-value|history-parameter)*>
<!ATTLIST metric
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    parmType CDATA #IMPLIED
    desc CDATA #IMPLIED
    protocol (SNMP|TL1|NAGIOS|SYSTEM|METRIC|CORBA|SERVICE|ASCII|API) #REQUIRED
    units CDATA #IMPLIED
    conversion-function (NONE|PER_PERIOD|PER_SECOND|PER_PERIOD_PER_SECOND|TIMES_SECOND|PER_PERIOD_TIMES_SECOND) #REQUIRED
    consolidation-function (SUM|AVG|MIN|MAX) #REQUIRED

    location (NA|NEAR_END|FAR_END) #IMPLIED
    direction (NA|RECEIVE|TRANSMIT|BOTH) #IMPLIED

    min CDATA #IMPLIED
    max CDATA #IMPLIED
    displayType CDATA #IMPLIED
    displayColor (BLUE|RED|ORANGE|YELLOW|MAGENTA|INDIGO|GREEN|VIOLET|DARK_BLUE|DARK_RED|DARK_ORANGE|DARK_YELLOW|DARK_MAGENTA|DARK_INDIGO|DARK_GREEN|DARK_VIOLET) #IMPLIED
    minmaxDisplayColor (BLUE|RED|ORANGE|YELLOW|MAGENTA|INDIGO|GREEN|VIOLET|DARK_BLUE|DARK_RED|DARK_ORANGE|DARK_YELLOW|DARK_MAGENTA|DARK_INDIGO|DARK_GREEN|DARK_VIOLET) #IMPLIED 
    hidePm (y|Y|n|N|true|false) #IMPLIED
    alwaysDisplayInPmPage (y|Y|n|N|true|false) #IMPLIED

    testValue CDATA #IMPLIED
    
    licenses CDATA #IMPLIED
  >

<!ELEMENT parameter (discriminator)*>
<!ATTLIST parameter
    name CDATA #REQUIRED
    collector (SNMP|TL1|NAGIOS|OBJECT|METRIC|CORBA|SERVICE|ASCII|SYSTEM|API) #IMPLIED
    oid CDATA #IMPLIED
    type (COUNTER|GAUGE) #IMPLIED
    indexed (true|TRUE|1|false|0|FALSE) #IMPLIED
    regex CDATA #IMPLIED
    aggregation-function (COUNT|SUM|AVG|MIN|MAX|VALUE_1|VALUE_2|VALUE_3|VALUE_4|VALUE_5|VALUE_6|VALUE_7|VALUE_8) #IMPLIED
    discriminator-function (AND|OR) #IMPLIED
    onResynchOid CDATA #IMPLIED
    oidSuffix CDATA #IMPLIED
    index-type (DEFAULT|OBJECT_PROPERTY) #IMPLIED
    index CDATA #IMPLIED
    index-converter (DECIMAL_TO_HEX|HEX_TO_DECIMAL|NONE) #IMPLIED
    index-input-separator CDATA #IMPLIED
    index-output-separator CDATA #IMPLIED
    pm-generator CDATA #IMPLIED
  >

<!ELEMENT discriminator EMPTY>
<!ATTLIST discriminator
   name CDATA #REQUIRED
   type (COLUMN) #REQUIRED
   oid CDATA #IMPLIED
   regex CDATA #IMPLIED
  >

<!ELEMENT min EMPTY>
<!ATTLIST min
    parameter CDATA #IMPLIED
    rpn CDATA #IMPLIED
  >

<!ELEMENT value EMPTY>
<!ATTLIST value
    parameter CDATA #IMPLIED
    rpn CDATA #IMPLIED
  >

<!ELEMENT max EMPTY>
<!ATTLIST max
    parameter CDATA #IMPLIED
    rpn CDATA #IMPLIED
  >
<!-- oidSuffix in history parameter will append (.1) by default.Do not explicitly specify (.1) in oidSuffix -->
<!ELEMENT history-parameter EMPTY>
<!ATTLIST history-parameter
    name CDATA #REQUIRED
    collector (SNMP|TL1|NAGIOS|OBJECT|METRIC|CORBA|SERVICE|ASCII|API) #IMPLIED
    oid CDATA #IMPLIED
    type (COUNTER|GAUGE) #IMPLIED
    indexed (true|TRUE|1|false|0|FALSE) #IMPLIED
    onResynchOid CDATA #IMPLIED
    oidSuffix CDATA #IMPLIED
  >

<!ELEMENT history-value EMPTY>
<!ATTLIST history-value
    parameter CDATA #IMPLIED
    rpn CDATA #IMPLIED
  >

=== rupeshpurum/Shell-Scripts/TL1/profiles/fujitsu-flashwave-9500.pro_FILES/fujitsu-flashwave-9500/pm/coe-evc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pmProfile PUBLIC "pm/pmProfile.dtd" "pmProfile.dtd">

<pmProfile name="coe-evc" version="570e6fa4b46f">
  <metricGroup name="EVC metrics" id="coe-evc.metrics" protocol="SERVICE" displayType="Normal">
    <metric id="coe-evc.one-way-delay" name="EVC One Way delay SD" parmType="COE_ONEWAY_FRAME_DELAY_SD" desc="EVC One-way delay Source to Destination" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Milliseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="BLUE">
      <parameter name="oneWayDelay" collector="SERVICE" oid="IP_SLA_ONEWAY_DELAY_SD" type="GAUGE" indexed="false"/>
      <value rpn="oneWayDelay,1000,/"/>
    </metric>
    <metric id="coe-evc.one-way-delay-ds" name="EVC One Way delay DS" parmType="COE_ONEWAY_FRAME_DELAY_DS" desc="EVC One-way delay Destination to Source" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Milliseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="oneWayDelayDs" collector="SERVICE" oid="IP_SLA_ONEWAY_DELAY_DS" type="GAUGE" indexed="false"/>
      <value rpn="oneWayDelayDs,1000,/"/>
    </metric>
    <metric id="coe-evc.two-way-delay" name="EVC Two Way delay" parmType="COE_TWOWAY_FRAME_DELAY" desc="EVC Two-way delay" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Milliseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="twoWayDelay" collector="SERVICE" oid="IP_SLA_RTT" type="GAUGE" indexed="false"/>
      <value rpn="twoWayDelay,1000,/"/>
    </metric>
    <metric id="coe-evc.one-way-jitter" name="EVC One Way Jitter SD" parmType="COE_ONEWAY_FRAME_DELAY_VAR_SD" desc="EVC One-way Jitter Source to Destination" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Microseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="BLUE">
      <parameter name="oneWayJitter" collector="SERVICE" oid="IP_SLA_LATENCY_SD" type="GAUGE" indexed="false"/>
      <value rpn="oneWayJitter,0,+"/>
    </metric>
    <metric id="coe-evc.one-way-jitter-ds" name="EVC One Way Jitter DS" parmType="COE_ONEWAY_FRAME_DELAY_VAR_DS" desc="EVC One-way Jitter Destination to Source" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Microseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="oneWayJitterDs" collector="SERVICE" oid="IP_SLA_LATENCY_DS" type="GAUGE" indexed="false"/>
      <value rpn="oneWayJitterDs,0,+"/>
    </metric>
    <metric id="coe-evc.two-way-jitter" name="EVC Two Way Jitter" parmType="COE_TWOWAY_FRAME_DELAY_VAR" desc="EVC Two-way Jitter" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Microseconds" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="twoWayJitter" collector="SERVICE" oid="IP_SLA_JITTER" type="GAUGE" indexed="false"/>
      <value rpn="twoWayJitter,0,+"/>
    </metric>
    <metric id="coe-evc.frame-loss-in-evc" name="EVC Frame Loss" parmType="COE_FRAME_LOSS_RATIO" desc="EVC Frame loss" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="frames" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="frameLoss" collector="SERVICE" oid="IP_SLA_FRAMELOSS_RATIO" type="GAUGE" indexed="false"/>
      <value rpn="frameLoss,0,+"/>
    </metric>
    <metric id="coe-evc.evc-uptime" name="EVC Uptime" parmType="STATE_UPTIME" desc="EVC Uptime" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="milliseconds" conversion-function="PER_PERIOD" consolidation-function="SUM" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="upTime" collector="OBJECT" oid="upTime" type="COUNTER" indexed="false"/>
      <parameter name="timeStampUpToDown" collector="OBJECT" oid="timeStampUpToDown" type="COUNTER" indexed="false"/>
      <parameter name="timeStampDownToUp" collector="OBJECT" oid="timeStampDownToUp" type="COUNTER" indexed="false"/>
      <parameter name="currentPollTime" collector="SYSTEM" oid="POLL_TIME" type="COUNTER" indexed="false"/>
      <value rpn="timeStampDownToUp,timeStampUpToDown,GT,upTime,currentPollTime,timeStampDownToUp,-,+,upTime,IF"/>
    </metric>
    <metric id="coe-evc.evc-downtime" name="EVC Downtime" parmType="STATE_DOWNTIME" desc="EVC Downtime" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="milliseconds" conversion-function="PER_PERIOD" consolidation-function="SUM" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="downTime" collector="OBJECT" oid="downTime" type="COUNTER" indexed="false"/>
      <parameter name="timeStampUpToDown" collector="OBJECT" oid="timeStampUpToDown" type="COUNTER" indexed="false"/>
      <parameter name="timeStampDownToUp" collector="OBJECT" oid="timeStampDownToUp" type="COUNTER" indexed="false"/>
      <parameter name="currentPollTime" collector="SYSTEM" oid="POLL_TIME" type="COUNTER" indexed="false"/>
      <value rpn="timeStampUpToDown,timeStampDownToUp,GT,downTime,currentPollTime,timeStampUpToDown,-,+,downTime,IF"/>
    </metric>
    <metric id="coe-evc.availablility-in-evc" name="EVC Availability" parmType="COE_AVAILABILITY" desc="EVC Availability" protocol="METRIC" licenses="ETHERNET_ASSURANCE" units="%" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="upTimeMetric" collector="METRIC" oid="STATE_UPTIME" type="COUNTER"/>
      <parameter name="downTimeMetric" collector="METRIC" oid="STATE_DOWNTIME" type="COUNTER"/>
      <value rpn="upTimeMetric,upTimeMetric,downTimeMetric,+,/,100,*"/>
    </metric>
    <metric id="coe-evc.evc-rx-avg-mbps" name="EVC Rx Avg Throughput" parmType="COE_RX_AVG_MBPS" desc="EVC average Mbps received" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Mbps" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="rxAvgMbps" collector="SERVICE" oid="ETH_RX_BANDWIDTH" type="GAUGE" indexed="false"/>
      <value rpn="rxAvgMbps,1000000,/"/>
    </metric>
    <metric id="coe-evc.evc-tx-avg-mbps" name="EVC Tx Avg Throughput" parmType="COE_TX_AVG_MBPS" desc="EVC average Mbps transmitted" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Mbps" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="BLUE">
      <parameter name="txAvgMbps" collector="SERVICE" oid="ETH_TX_BANDWIDTH" type="GAUGE" indexed="false"/>
      <value rpn="txAvgMbps,1000000,/"/>
    </metric>
    <metric id="coe-evc.throughput-of-evc" name="EVC Max Avg Throughput" parmType="COE_THROUGHPUT" desc="EVC Max Avg Mbps" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="Mbps" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="rxAvg" collector="SERVICE" oid="ETH_RX_BANDWIDTH" type="GAUGE" indexed="false"/>
      <parameter name="txAvg" collector="SERVICE" oid="ETH_TX_BANDWIDTH" type="GAUGE" indexed="false"/>
      <value rpn="rxAvg,txAvg,MAX"/>
    </metric>
    <metric id="coe-evc.rx-utilization-of-evc" name="EVC Rx Avg Utilization" parmType="COE_RX_UTILIZATION" desc="EVC Rx Avg Utilization" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="%" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="rxUtil" collector="SERVICE" oid="ETH_RX_UTILIZATION" type="GAUGE" indexed="false"/>
      <value rpn="rxUtil,0,+"/>
    </metric>
    <metric id="coe-evc.tx-utilization-of-evc" name="EVC Tx Avg Utilization" parmType="COE_TX_UTILIZATION" desc="EVC Tx Avg Utilization" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="%" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="BLUE">
      <parameter name="txUtil" collector="SERVICE" oid="ETH_TX_UTILIZATION" type="GAUGE" indexed="false"/>
      <value rpn="txUtil,0,+"/>
    </metric>
    <metric id="coe-evc.utilization-of-evc" name="EVC Max Utilization" parmType="COE_UTILIZATION" desc="EVC Max Utilization" protocol="SERVICE" licenses="ETHERNET_ASSURANCE" units="%" conversion-function="NONE" consolidation-function="AVG" displayType="lineSeries-hist" displayColor="DARK_GREEN">
      <parameter name="rxutilization" collector="SERVICE" oid="ETH_RX_UTILIZATION" type="GAUGE" indexed="false"/>
      <parameter name="txutilization" collector="SERVICE" oid="ETH_TX_UTILIZATION" type="GAUGE" indexed="false"/>
      <value rpn="rxutilization,txutilization,MAX"/>
    </metric>
  </metricGroup>
</pmProfile>
